### ISSUE TITLE
MIME type ('text/plain') is not executable

### ISSUE THREAD

**Issue by leis1** [yqcs/heartsk_community#3]
![Snipaste_2022-06-10_20-18-40](https://user-images.githubusercontent.com/14808529/173062789-505da238-66be-4f30-8edf-bd018bba943c.png)

Refused to execute script from 'http://127.0.0.1/static/umi.91bbbd87.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

https://blog.csdn.net/zhuyiquan/article/details/52173735

**Comment by yqcs** [comment]
等会

**Comment by yqcs** [comment]
我刚在新电脑测试，正常使用啊。请确认下载的是BUG@1.0.1版本
